---
title: "data wrangling ii"
output: github_document
---

## Load library

```{r}
library(tidyverse)
```

## Load data and clean column names

```{r}
options(tibble.print_min = 3)

litters_data = read_csv("./data/FAS_litters.csv")
litters_data = janitor::clean_names(litters_data)

pups_data = read_csv("./data/FAS_pups.csv")
pups_data = janitor::clean_names(pups_data)
```

## `select`

lets select some columns.

```{r}
select(litters_data, group, litter_number)
select(litters_data, group, gd0_weight, gd18_weight)

select(litters_data, group, gd0_weight:gd_of_birth)
select(litters_data, group, starts_with("pups"))

select(litters_data, -litter_number)

select(litters_data, GROUP = group, litter_number)

rename(litters_data, GROUP = group)

select(litters_data, litter_number, everything())

relocate(litters_data, litter_number)
```

## Learning Assessment

Learning Assessment: In the pups data, select the columns containing litter number, sex, and PD ears

```{r}
select(pups_data, litter_number, sex, pd_ears)
```

## `filter`

Getting rid of rows

```{r}
filter(litters_data, gd_of_birth == 20)
filter(litters_data, group == "Con7")

filter(litters_data, gd0_weight < 23)

filter(litters_data, pups_survive != 4)

filter(litters_data, !(group == "Con7"))

filter(litters_data, group %in% c("Con7", "COn8"))

filter(litters_data, group == "Con7", gd_of_birth == 20)

filter(litters_data, group == "Con7" | gd_of_birth == 20)

drop_na(litters_data)
drop_na(litters_data, gd0_weight)
```

## `mutate`

Adding/changing columns

```{r}
mutate(litters_data, weight_change = gd18_weight - gd0_weight)

mutate(
  litters_data,
  weight_change = gd18_weight - gd0_weight,
  group = str_to_lower(group)
)
```

## `arrange`

rearrangement

```{r}
arrange(litters_data, gd_of_birth, gd0_weight)
```

## Pipes

```{r}
litters_df = 
  read_csv("data/FAS_litters.csv") %>%
  janitor::clean_names() %>%
  select(group, pups_survive) %>%
  filter(group == "Con7")


litters_df = 
  read_csv("data/FAS_litters.csv") %>% 
  janitor::clean_names() %>% 
  select(-pups_survive) %>% 
  mutate(
    weight_change = gd18_weight - gd0_weight,
    group = str_to_lower(group)
  ) %>% 
  drop_na(weight_change) %>% 
  filter(group %in% c("Con7", "COn8")) %>% 
  select(litter_number, group, weight_change, everything())
```

Shortcut for %>% is shift+ctrl+M